---
- name: Update system packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Docker build directory
  file:
    path: /tmp/jenkins-docker
    state: directory
    mode: "0755"

- name: Create plugins.txt file
  copy:
    dest: /tmp/jenkins-docker/plugins.txt
    content: |
      pipeline-stage-view:latest
      git:latest
      workflow-aggregator:latest
      blueocean:latest
      ansible:latest
      antisamy-markup-formatter:latest
      authorize-project:latest
      build-timeout:latest
      cloudbees-folder:latest
      configuration-as-code:latest
      credentials-binding:latest
      email-ext:latest
      git:latest
      github-branch-source:latest
      gradle:latest
      ldap:latest
      mailer:latest
      matrix-auth:latest
      pam-auth:latest
      pipeline-github-lib:latest
      ssh-slaves:latest
      timestamper:latest
      workflow-aggregator:latest
      ws-cleanup:latest
      pipeline-stage-view:2.34
      job-dsl:latest
      workflow-job:latest
      workflow-cps:latest
      terraform:latest
      kubernetes-cli:latest
      ansible:latest

    
- name: Create JCasC configuration file
  copy:
    dest: /tmp/jenkins-docker/casc.yaml
    content: |
      jenkins:
        securityRealm:
          local:
            allowsSignup: false
            users:
              - id: "admin"
                password: "admin"
        authorizationStrategy:
          loggedInUsersCanDoAnything:
            allowAnonymousRead: false
        systemMessage: "Jenkins configured as code with Docker"

- name: Create job configuration file
  copy:
    dest: /tmp/jenkins-docker/job-config.xml
    content: |
      <flow-definition plugin="workflow-job@1508.v9cb_c3a_a_89dfd">
        <actions>
          <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobAction plugin="pipeline-model-definition@2.2247.va_423189a_7dff"/>
          <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobPropertyTrackerAction plugin="pipeline-model-definition@2.2247.va_423189a_7dff">
            <jobProperties/>
            <triggers/>
            <parameters/>
            <options/>
          </org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobPropertyTrackerAction>
        </actions>
        <description>Job created via Ansible</description>
        <keepDependencies>false</keepDependencies>
        <properties>
          <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
            <triggers>
              <hudson.triggers.SCMTrigger>
                <spec>* * * * *</spec>
                <ignorePostCommitHooks>false</ignorePostCommitHooks>
              </hudson.triggers.SCMTrigger>
            </triggers>
          </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
        </properties>
        <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@4050.v8b_a_69b_587c39">
          <scm class="hudson.plugins.git.GitSCM" plugin="git@5.7.0">
            <configVersion>2</configVersion>
            <userRemoteConfigs>
              <hudson.plugins.git.UserRemoteConfig>
                <url>https://github.com/MayElbaz18/Monithor-EnvironmentSetup.git</url>
              </hudson.plugins.git.UserRemoteConfig>
            </userRemoteConfigs>
            <branches>
              <hudson.plugins.git.BranchSpec>
                <name>*/main</name>
              </hudson.plugins.git.BranchSpec>
            </branches>
            <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
            <submoduleCfg class="empty-list"/>
            <extensions/>
          </scm>
          <scriptPath>Jenkinsfile</scriptPath>
          <lightweight>true</lightweight>
        </definition>
        <disabled>false</disabled>
      </flow-definition>

- name: Create docker-compose.yml file
  copy:
    dest: /tmp/jenkins-docker/docker-compose.yml
    content: |
      version: "3.8"
      services:
        jenkins:
          build:
            context: .
          ports:
            - 8080:8080
          volumes:
            - jenkins_data:/var/jenkins_home
      volumes:
        jenkins_data:

- name: Create Dockerfile for Jenkins
  copy:
    dest: "/tmp/jenkins-docker/Dockerfile"
    content: |
      FROM jenkins/jenkins:lts
      ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      ENV JENKINS_USER="admin"
      ENV JENKINS_PASS="admin"

      USER root
      RUN apt-get update && apt-get install -y curl git jq && apt-get clean

      USER jenkins

      COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
      RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt
      
      COPY casc.yaml /var/jenkins_home/casc.yaml
      ENV CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml

      COPY job-config.xml /usr/share/jenkins/ref/jobs/MoniThorDeployment/config.xml

- name: Build Jenkins Docker image
  command: docker-compose build
  args:
    chdir: /tmp/jenkins-docker
  register: build_result
  ignore_errors: true

- name: Debug Docker build output
  debug:
    var: build_result
  when: build_result.failed

- name: Check Docker build status
  fail:
    msg: "Docker build failed. Please check the debug output above."
  when: build_result.failed

- name: Start Jenkins container
  command: docker-compose up -d
  args:
    chdir: /tmp/jenkins-docker
  register: startup_result
  ignore_errors: true

- name: Debug Docker startup output
  debug:
    var: startup_result
  when: startup_result.failed

- name: Check Docker startup status
  fail:
    msg: "Docker startup failed. Please check the debug output above."
  when: startup_result.failed

- name: Wait for Jenkins to be ready
  uri:
    url: "http://{{ ansible_host }}:8080/login?from=%2F"
    user: "admin"
    password: "admin"
    method: GET
    status_code: 200
  retries: 10
  delay: 15

- name: Verify Jenkins job creation
  uri:
    url: "http://{{ ansible_host }}:8080/login?from=%2Fjob%2FMoniThorDeployment%2Fapi%2Fjson"
    user: "admin"
    password: "admin"
    method: GET
    status_code: 200

- name: Print output to console
  debug:
    msg: "Jenkins job created successfully http://{{ ansible_host }}:8080"